on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./

      - run: |
          date > dummy.txt
          git add dummy.txt
          git commit -m "chore: update dummy"
          # git push
          
      - name: Commit User
        run: |
          printf "user.name:  " && git log -1 --pretty=format:'%an' && echo
          printf "user.email: " && git log -1 --pretty=format:'%ae' && echo
      - name: Config User
        run: |     
          printf "user.name:  " && git config user.name && echo
          printf "user.email: " && git config user.email && echo
      
